#!/usr/bin/bash

if [ $# -ne 1 ]; then
	echo "invalid argument(s)"
	exit 1
fi

input_path=$1 
if [ ! -d "$input_path" ]; then
	echo "$input_path is not a directory"
	exit 1
fi

abs_path=$(cd "$input_path"; pwd)
dir_name=$(basename "$abs_path")

tmux new-session -t "$dir_name" -c "$abs_path"
